### ISSUE TITLE
Crash during worldgen and world load

### ISSUE THREAD

**Issue by MopsTMC** [FrozenBlock/FrozenLib#10]
**Description of the Bug Encountered**
I seem to be getting the same issue mentioned in [FrozenBlock/WilderWild#198](https://github.com/FrozenBlock/WilderWild/issues/198) even though I'm running the latest version of either mods

**Logs**
[Log](https://mclo.gs/tlTRzEN) (Line 1152)
[Crash Report](https://mclo.gs/RSPKc8J)

**Comment by AViewFromTheTop** [comment]
Should be fixed in 1.1.8.

**Comment by MopsTMC** [comment]
Indeed, hadn't had time to test it up until now
