### ISSUE TITLE
Surface Rule Injections Break C2ME Worldgen

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/FrozenLib#20]

**Comment by Treetrain1** [comment]
wait c2me might've fixed this
https://modrinth.com/mod/c2me-fabric/version/0.2.0+alpha.10.84+1.20-rc1

**Comment by AViewFromTheTop** [comment]
> wait c2me might've fixed this https://modrinth.com/mod/c2me-fabric/version/0.2.0+alpha.10.84+1.20-rc1

that's only for the quilt version of our implementation though
i dont think that actually applies to *our* (though now its really just your) implementation of it

**Comment by AViewFromTheTop** [comment]
ill test really quick

**Comment by AViewFromTheTop** [comment]
@Treetrain1 ok no that fixed it uh
wtf

**Comment by Treetrain1** [comment]
honestly do we even need QSL surface rules?

**Comment by Treetrain1** [comment]
since we have our own solution (and it may possibly be even better)

**Comment by AViewFromTheTop** [comment]
> honestly do we even need QSL surface rules?

NOPE lmao
your version is infinitely better
even my version, despite being bloated dogshit, was also better

**Comment by AViewFromTheTop** [comment]
by the way
i think we should try to find a way to make a surface rule that uses biome tags, BUT somehow converts that to a list of biomes each time the datapack is reloaded (or upon loading a world)
checking if the biome's in a tag causes a LOT of lag, especially for surface rules so it'd be easier if it was somehow converted to a list only once
@Treetrain1

**Comment by Treetrain1** [comment]
> by the way i think we should try to find a way to make a surface rule that uses biome tags, BUT somehow converts that to a list of biomes each time the datapack is reloaded (or upon loading a world) checking if the biome's in a tag causes a LOT of lag, especially for surface rules so it'd be easier if it was somehow converted to a list only once @Treetrain1

could probably just reference the existing biome condition source

**Comment by AViewFromTheTop** [comment]
idk i think it's more complex than that

**Comment by Treetrain1** [comment]
> idk i think it's more complex than that

well i think surface rules are only accessed after the initial datapack load
so i think it would work

**Comment by AViewFromTheTop** [comment]
> well i think surface rules are only accessed after the initial datapack load so i think it would work

after,,,
oh.
ok

**Comment by Treetrain1** [comment]
> > honestly do we even need QSL surface rules?
> 
> NOPE lmao your version is infinitely better even my version, despite being bloated dogshit, was also better

should i just remove it right now

**Comment by Treetrain1** [comment]
the only thing it has that we dont is datapackable event callbacks

**Comment by Treetrain1** [comment]
> the only thing it has that we dont is datapackable event callbacks

but i dont see a use of that for us

**Comment by Treetrain1** [comment]
> > the only thing it has that we dont is datapackable event callbacks
> 
> but i dont see a use of that for us

unless we do some weird "Configurable ...." mod

**Comment by AViewFromTheTop** [comment]
> should i just remove it right now

yea
