### ISSUE TITLE
Removable Item Tags Removed From Stone Chests Upon Interaction (ItemStack tick method called when in *all* inventories)

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/FrozenLib#26]
Read title
Please help @Treetrain1
It previously only ticked when in the players inventory but now it ticks even when it’s in the chest (change from Mojang)
Because of that change, ancient items get their tags removed while in stone chests

**Comment by AViewFromTheTop** [comment]
im having zero luck fixing this.
something horrible mustve happened what the hell is causing this itisnt good

**Comment by AViewFromTheTop** [comment]
@Treetrain1 just making sure you saw this
we *need* this fixed before we release ww 2.1 because it completely ruins stone chests

**Comment by Treetrain1** [comment]
oh?

**Comment by Treetrain1** [comment]
all i know is the problem is definitely in `ItemStackMixin.isSameItemSameTags()`

**Comment by AViewFromTheTop** [comment]
> all i know is the problem is definitely in `ItemStackMixin.frozenLib$removeTagsAndCompare()`

I know but that never was an issue before
And if we remove that, then you won’t be able to shift-click items

**Comment by AViewFromTheTop** [comment]
But like what changed why is it now an issue

**Comment by Treetrain1** [comment]
found a fix

**Comment by Treetrain1** [comment]
> found a fix

but im not too sure how much it affects other things

**Comment by AViewFromTheTop** [comment]
> > found a fix
> 
> but im not too sure how much it affects other things

POGGGGGGGGGG YOURE A GENIUSSSSS
feel free to push on my PR and i'll test it for you

**Comment by Treetrain1** [comment]
all i did was make a boolean if its in a container
then just when the container is checking it it prevents it from removing it lol

shift clicking seems to work

**Comment by AViewFromTheTop** [comment]
> all i did was make a boolean if its in a container then just when the container is checking it it prevents it from removing it lol
> 
> shift clicking seems to work

how the fuck did you do that.
i was trying to do that for HOURS yesterday and i couldnt figure out a way to make it work

**Comment by Treetrain1** [comment]
hold on ill just commit to upstream 1.20

**Comment by AViewFromTheTop** [comment]
@Treetrain1 it ALMOST works as intended, but shift-clicking doesn't work
still, this is 573% better than what it was before thank you so much

**Comment by Treetrain1** [comment]
shift clicking doesnt work??

**Comment by AViewFromTheTop** [comment]
> shift clicking doesnt work??

it doesnt
it shifts the item into the inventory, but the tag is removed *AFTER* the shift click
so i just tried shift clicking amethyst into my inv from the chest and it went into like eight different slots instead of just merging into one

**Comment by Treetrain1** [comment]
new idea

what if it adds it back after its done checking

**Comment by AViewFromTheTop** [comment]
> new idea
> 
> what if it adds it back after its done checking

that could work but i have no clue how to do it honestly lmao
could you do that please

**Comment by Xfrtrex** [comment]
a friend pointed out how hard it is to get colored mesoglea blocks, anything you can think of to fix it?

**Comment by Treetrain1** [comment]
> > new idea
> > what if it adds it back after its done checking
> 
> that could work but i have no clue how to do it honestly lmao could you do that please

i tried i couldnt get it to work 💀

**Comment by Treetrain1** [comment]
> > > new idea
> > > what if it adds it back after its done checking
> > 
> > 
> > that could work but i have no clue how to do it honestly lmao could you do that please
> 
> i tried i couldnt get it to work 💀

wait nvm im so stupid i was using the same tag object instead of making a copy

**Comment by Treetrain1** [comment]
> 

nvm im still stupid

**Comment by AViewFromTheTop** [comment]
> a friend pointed out how hard it is to get colored mesoglea blocks, anything you can think of to fix it?

Kill more jellyfish

**Comment by AViewFromTheTop** [comment]
> Kill more jellyfish

I’m probably gonna switch jelly food too seaweed or algae
Which one do you prefer

**Comment by AViewFromTheTop** [comment]
@Treetrain1 why not just make the merge thing work if one stack is in the inventory and another’s in a container
All you’ll have to do is just add a Boolean method to the interface

**Comment by Treetrain1** [comment]
> @Treetrain1 why not just make the merge thing work if one stack (or both) is in the inventory and another’s in a container All you’ll have to do is just add a Boolean method to the interface

no clue how to do that ima be real

**Comment by AViewFromTheTop** [comment]
> > @Treetrain1 why not just make the merge thing work if one stack (or both) is in the inventory and another’s in a container All you’ll have to do is just add a Boolean method to the interface
> 
> no clue how to do that ima be real

Man come on it’s so straightforward and so much easier than like everything else you’ve done lol

**Comment by Treetrain1** [comment]
> > > @Treetrain1 why not just make the merge thing work if one stack (or both) is in the inventory and another’s in a container All you’ll have to do is just add a Boolean method to the interface
> > 
> > 
> > no clue how to do that ima be real
> 
> Man come on it’s so straightforward and so much easier than like everything else you’ve done lol

idk how to track if its in a container or the player's inventory

**Comment by AViewFromTheTop** [comment]
> idk how to track if its in a container or the player's inventory

dude didn't you literally just do that yesterday

**Comment by Treetrain1** [comment]
> > idk how to track if its in a container or the player's inventory
> 
> dude didn't you literally just do that yesterday

not exactly

**Comment by AViewFromTheTop** [comment]
> not exactly

oh lol you made the setInContainer method always true instead of setting to the parameter

**Comment by Treetrain1** [comment]
> > not exactly
> 
> oh lol you made the setInContainer method always true instead of setting to the parameter

☠️

**Comment by AViewFromTheTop** [comment]
> ☠️

@Treetrain1 well i fixed it but it still doesnt fix stack merging

**Comment by AViewFromTheTop** [comment]
@Xfrtrex what should jellyfish eat for reproduction

**Comment by Xfrtrex** [comment]
![image](https://github.com/FrozenBlock/FrozenLib/assets/80720298/52196095-d780-4f27-ab15-714fe21b487c)

**Comment by AViewFromTheTop** [comment]
> ![image](https://user-images.githubusercontent.com/80720298/251634277-52196095-d780-4f27-ab15-714fe21b487c.png)

Yea I’ve already done research
The current lists are:
Normal Jellies: Kelp, Seagrass, Algae, Cod, Salmon
Pearlescent Jellies: Any Nematocyst, Cod, Salmon
Those are quite broad and I just want to simplify it
Should it just be Cod and Salmon? Or should it just be Kelp? Seagrass? What do you think?

**Comment by Xfrtrex** [comment]
probably just any fish.

**Comment by AViewFromTheTop** [comment]
> probably just any fish.

ill do cod and salmon since they currently dont sting tropical fish and puffers (itd cause lag in warm oceans)

**Comment by Treetrain1** [comment]
Oh yeah I fixed this
can close now
