### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by LIUKRAST** [FrozenBlock/FrozenLib#3]
- [x] Registering custom entities skin/sounds depending on the name without mixins
- [x] Connected blocks (Optifine like)
- [x] Almost anything else you would like to "register". Let me explain better

Most times you have to mixin stuff to call events or change vanilla stuff. Since most time you mixin entities/entity renderers you just make a lot of useless mixins that you don't even need. You can just collapse all of them in one and add a registry system (yes, like how you register a new block in the game, it just does like Frozenblock.register(Registry.CUSTOM_SKIN, String customname, String skinpath)

Not just that, you can register a new model modifier system to easy stuff

- [x] Config system. I know you guys are using in-game configs but I think that it would be a cool idea if there's also a "txt" possibility just in case. Overriding in-game menus is not reccomended btw.

These are my ideas for now, hope that these can help someway

**Comment by LIUKRAST** [comment]
Also @AViewFromTheTop how do I get frozenLib on intellij? It asks if I want to import it as a gradle or maven. I know it's a maven buy maybe to work on it i have to get it as a gradle? So yeah idk xD

Also tell me whatever new implementiom you would like. I tried to code games in java recently and i understood a way more of this really complex language xD

**Comment by AViewFromTheTop** [comment]
> Also @AViewFromTheTop how do I get frozenLib on intellij? It asks if I want to import it as a gradle or maven. I know it's a maven buy maybe to work on it i have to get it as a gradle? So yeah idk xD
> 
> Also tell me whatever new implementiom you would like. I tried to code games in java recently and i understood a way more of this really complex language xD

I have no idea, Treetrain's the wizard that got the complex part of this (letting it update live between multiple projects) working

As for new things, I suppose finding a way to use that registry thing BEFORE said classes are already finally loaded.
For example, I tried to make a spawn override mixin with that idea. It didn't work, as you need to already be able to override said things AS the class is loading, using a ModInitializer and THEN doing the registry is too late for that.

**Comment by AViewFromTheTop** [comment]
@LIUKRAST Oh, also! It would be absolutely amazing if you could make some sort of "Automatic Wood-Set Asset Generator" thing. That'd save tons of time. Just plug in the wood's name and the mod's id, and boom. Done.

**Comment by AViewFromTheTop** [comment]
Also yeah we definitely need a custom config system

**Comment by Treetrain1** [comment]
Wouldn't connected blocks just need another mod like Continuity?

**Comment by Treetrain1** [comment]
> @LIUKRAST Oh, also! It would be absolutely amazing if you could make some sort of "Automatic Wood-Set Asset Generator" thing. That'd save tons of time. Just plug in the wood's name and the mod's id, and boom. Done. Now you've got all the blockstates, models, item models, etc.

moonlight lib moment

**Comment by Treetrain1** [comment]
Connected blocks completed via Fabric Block Appearance API

**Comment by Treetrain1** [comment]
Complete
