### ISSUE TITLE
FrozenLib 1.5.4 breaks specific designs of shulker farms.

### ISSUE THREAD

**Issue by fleefie** [FrozenBlock/FrozenLib#38]
Shulker farms designed around forcing a shulker to shoot upwards through scaffolding break when FrozenLib is installed. I know, it's strangely specific, but it happens.

**Steps To Reproduce**

1. Install Fabric 0.15.3, Fabric API 0.91.0, ClothConfig 11.1.118 and FrozenLib 1.5.4
2. Use a contraption based around forcing a Shulker to shoot through scaffolding
3. Watch as somehow, the bullets collide with the scaffolding.

**Expected Behavior**

Shulker bullets should shoot through the scaffolding

**Screenshots**

![2024-01-10_15 18 49](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/assets/64854248/661d445c-4eaa-4138-a4ab-d6ce1727a43b)
![2024-01-10_15 24 59](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/assets/64854248/aa1b9ea0-f8e4-42de-8845-a68e0a95ce56)

Shulker containment above. Farm design is by Ianxofour, [world download](https://www.mediafire.com/file/cgfshdk16jifi8l/IanXO4%2527s_Instant_Shulker_Farm.zip/file), and [associated showcase video](https://www.youtube.com/watch?v=4KzL5aw4MiE)

**Logs**

https://mclo.gs/B22F5r2 I see no issues there

**Additional context**

This issue originally came from the mod Simple Copper Pipes, which embeds this library. I tracked it from a whole modpack all the way to this repo. [Link to the issue from Simple Copper Pipes](https://github.com/AViewFromTheTop/SimpleCopperPipesMC/issues/27)

**Comment by fleefie** [comment]
Did some more testing. Seems that it works fine in 1.3.12 but breaks in 1.3.13 onwards.

**Comment by AViewFromTheTop** [comment]
> Did some more testing. Seems that it works fine in 1.3.12 but breaks in 1.3.13 onwards, maybe it's related to the gravity API ?

@Treetrain1 moment

**Comment by AViewFromTheTop** [comment]
Fixed in future version 1.6.1.
