### ISSUE TITLE
Couldn't load tag frozenlib:dont_emit_use_game_events

### ISSUE THREAD

**Issue by MJRamon** [FrozenBlock/FrozenLib#45]
**Description of the Bug Encountered**
Couldn't load tag frozenlib:dont_emit_use_game_events as it is missing following references: deeperdarker:transmitter (from fabric)

**Steps To Reproduce**
1. Don't have Deeper Darker installed.
2. Start a game.

**Additional context**
Minecraft 1.20.1, Fabric 0.15.11, FrozenLib 1.7.2-Fabric+1.20.1 (bundled in Wilder Wild 2.4.2-Fabric+1.20.1)

**Comment by Treetrain1** [comment]
Neither Wilder Wild or FrozenLib interfaces with Deeper and Darker in any way. A third party mod must be causing this.
