### ISSUE TITLE
Game crashes when opening world with experimental settings

### ISSUE THREAD

**Issue by thwonn** [FrozenBlock/FrozenLib#52]
**The game crashes when trying to open a world with experimental settings enabled**

**Steps To Reproduce**
1. Enable "Remove experimental warning" in mod config
2. Create a world with experimental settings
3. Leave the world
4. Attempt to re-enter the world

**Expected Behavior**
The world loads

**Comment by AViewFromTheTop** [comment]
It’s disabled by default for this very reason- some other mods cause a crash with this for some reason.

**Comment by thwonn** [comment]
This did not happen with earlier versions of FrozenLib (before september 2024)
