### ISSUE TITLE
Crash on startup with the ExtraSounds mod.

### ISSUE THREAD

**Issue by GermanArtur** [FrozenBlock/FrozenLib#8]
Latest.log: https://pastebin.com/sPGRTNnq

Crash-client.txt: https://pastebin.com/gn8yeK3k

Modlist:
WilderWild-1.1.4-Fabric+1.19.2
cloth-config-8.2.88-fabric
extrasounds-2.3.1+1.19.2-1.19.1
fabric-api-0.68.0+1.19.2
fabric-language-kotlin-1.8.7+kotlin.1.7.22
FrozenLib-1.1.5-Fabric+1.19.2

**Comment by Treetrain1** [comment]
Fixed in 1.1.6,
included in Wilder Wild 1.1.5
