### ISSUE TITLE
Surface Rules Don't Get Applied When Opening Old Worlds

### ISSUE THREAD

**Issue by AViewFromTheTop** [FrozenBlock/FrozenLib#9]
That's the ACTUAL Oasis rule issue. Wetlands don't get their rules applied either.
We need this fixed ASAP for both 1.19.2 and 1.19.3.

**Comment by AViewFromTheEnd** [comment]
@Treetrain1 help
We’re gonna look like clowns if this doesn’t get fixed

**Comment by AViewFromTheTop** [comment]
gonna try to make my own surface rule thing so we dont look like dorks

**Comment by AViewFromTheTop** [comment]
im so sexy that i did it on my own

**Comment by AViewFromTheTop** [comment]
btw this means i've officially done something better than quilt LMFAO

**Comment by AViewFromTheTop** [comment]
oh also we can mixin modded dimensions too i think bruhhh

**Comment by Treetrain1** [comment]
> btw this means i've officially done something better than quilt LMFAO

Not exactly.
the problem could be just something i missed when porting

**Comment by AViewFromTheTop** [comment]
> > btw this means i've officially done something better than quilt LMFAO
> 
> Not exactly. the problem could be just something i missed when porting

someone was experiencing the same problem with dimensions added through quilt's system (where it only works on the first time the world starts) and i went through their surface rule api and your port literally works the EXACT same
you didnt miss anything lol

**Comment by AViewFromTheTop** [comment]
your port works better, if anything, because you actually added the stuff to rulesource9 instead of tacking the stuff onto the end of the return value
